# 检查强化学习控制器model

In [7]:
# ------- 来自于mujoco150在win+py3.9下的矫情的要求 --------
# 手动添加mujoco路径
import os
from getpass import getuser
user_id = getuser()
os.add_dll_directory(f"C://Users//{user_id}//.mujoco//mujoco200//bin")
os.add_dll_directory(f"C://Users//{user_id}//.mujoco//mujoco-py-2.0.2.0//mujoco_py")
# -------------------------------------------------------
import time
import argparse
import sys
import gym_custom_env       # 注册自定义环境
import gym
import numpy as np
import pybullet_envs
from stable_baselines3 import SAC, TD3, PPO
from mujoco_py.generated import const
from collections import deque

In [8]:
env = gym.make('HumanoidCustomEnv-v0')
#env.render(mode="human")
save_path = "sb3model/HumanoidCustomEnv-v0/2e6_t4_sac_HumanoidCustomEnv-v0/best_model.zip"

sac_model = SAC.load(save_path, env=env)
ppo_model = PPO.load('sb3model/HumanoidCustomEnv-v0/2e7_t10_cpu6_ppo_HumanoidCustomEnv-v0/best_model.zip',env=env)

============ HUMANOID CUSTOM ENV ============
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [9]:
# 手动设置policy_kwargs=dict(net_arch=[256, 256])的sac策略网络
sac_model.policy

SACPolicy(
  (actor): Actor(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (latent_pi): Sequential(
      (0): Linear(in_features=294, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (mu): Linear(in_features=256, out_features=17, bias=True)
    (log_std): Linear(in_features=256, out_features=17, bias=True)
  )
  (critic): ContinuousCritic(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (qf0): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=1, bias=True)
    )
    (qf1): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=2

In [10]:
# 手动设置policy_kwargs=dict(net_arch=[256, 256])的PPO策略网络
ppo_model.policy

ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential(
      (0): Linear(in_features=294, out_features=256, bias=True)
      (1): Tanh()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): Tanh()
    )
    (policy_net): Sequential()
    (value_net): Sequential()
  )
  (action_net): Linear(in_features=256, out_features=17, bias=True)
  (value_net): Linear(in_features=256, out_features=1, bias=True)
)

In [11]:
# PPO的默认策略网络
default_ppo_model = PPO.load('sb3model/HumanoidCustomEnv-v0/2e6_t4_ppo_HumanoidCustomEnv-v0.zip',env=env)
default_ppo_model.policy

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential()
    (policy_net): Sequential(
      (0): Linear(in_features=294, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=294, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
  )
  (action_net): Linear(in_features=64, out_features=17, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)

In [13]:
# SAC的默认策略网络
default_sac_model = SAC.load('sb3model/HumanoidCustomEnv-v0/2e6_t0_sac_HumanoidCustomEnv-v0.zip',env=env)
default_sac_model.policy
default_sac_model.predict

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


SACPolicy(
  (actor): Actor(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (latent_pi): Sequential(
      (0): Linear(in_features=294, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (mu): Linear(in_features=256, out_features=17, bias=True)
    (log_std): Linear(in_features=256, out_features=17, bias=True)
  )
  (critic): ContinuousCritic(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (qf0): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=1, bias=True)
    )
    (qf1): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=2

In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R


In [15]:
pos = np.array([0 , 1, 0, -0.35, 1.23e-06, 4.18e-08, 0.39,1,2])
quatanion = pos[3:7]
sum = np.linalg.norm(quatanion)
print(np.sum(quatanion*quatanion))
print(quatanion)
Rm = R.from_quat(quatanion)  # Rotation matrix
rotation_matrix = Rm.as_matrix()
print(rotation_matrix)
vertical_direction = np.array([0, 0, 1])
body_z_axis = rotation_matrix.dot(vertical_direction)
print(body_z_axis)
sum = np.linalg.norm(body_z_axis)
print(sum)
# 计算z轴方向向量与竖直向上方向向量的点积
dot_product = np.dot(body_z_axis, vertical_direction)
print(dot_product)

0.27460000000151463
[-3.50e-01  1.23e-06  4.18e-08  3.90e-01]
[[ 1.00000000e+00 -3.25420248e-06  3.38725419e-06]
 [-3.01673707e-06  1.07793154e-01  9.94173343e-01]
 [-3.60036417e-06 -9.94173343e-01  1.07793154e-01]]
[3.38725419e-06 9.94173343e-01 1.07793154e-01]
1.0
0.10779315367197961


# 检查XML

In [5]:
import os
from getpass import getuser
user_id = getuser()
os.add_dll_directory(f"C://Users//{user_id}//.mujoco//mujoco200//bin")
os.add_dll_directory(f"C://Users//{user_id}//.mujoco//mujoco-py-2.0.2.0//mujoco_py")
# -------------------------------------------------------
import time
import argparse
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath('checker.ipynb'))))
import gym_custom_env       # 注册自定义环境
import gym
import numpy as np
import pybullet_envs
from gym_custom_env.generateXML import HumanoidXML
import mujoco_py
import numpy as np
from mujoco_py.generated import const
from scipy.spatial.transform import Rotation as R

from stable_baselines3 import SAC, TD3, PPO

In [ ]:
def quaternion_to_rotation_matrix(q):  # x, y ,z ,w
    rot_matrix = np.array(
        [[1.0 - 2 * (q[1] * q[1] + q[2] * q[2]), 2 * (q[0] * q[1] - q[3] * q[2]), 2 * (q[3] * q[1] + q[0] * q[2])],
         [2 * (q[0] * q[1] + q[3] * q[2]), 1.0 - 2 * (q[0] * q[0] + q[2] * q[2]), 2 * (q[1] * q[2] - q[3] * q[0])],
         [2 * (q[0] * q[2] - q[3] * q[1]), 2 * (q[1] * q[2] + q[3] * q[0]), 1.0 - 2 * (q[0] * q[0] + q[1] * q[1])]],
        dtype=q.dtype)
    return rot_matrix

# params list
paramas = { 'torso_width':0.5,
            'init_position':[0,0,2.5],
            'pelvis_width':0.2,
            'upper_arm_lenth':0.31,
            'lower_arm_lenth':0.4,
            'shin_lenth':0.5,
            'torso_height':0.6,
            }

# 生成XML文件
t = HumanoidXML()
t.write_xml(file_path="ee.xml")


# 更新XML文件
t.set_params(paramas)
t.update_xml(file_path='ee.xml')

# 加载 XML 文件
# model = mujoco_py.load_model_from_path("gym_custom_env\\assets\\humanoid_custom.xml")
# model = mujoco_py.load_model_from_path("e.xml")
model = mujoco_py.load_model_from_path("humanoid.xml")
# 创建仿真环境和渲染器
sim = mujoco_py.MjSim(model)
viewer = mujoco_py.MjViewer(sim)

# 设置仿真时间步长和仿真时长
dt = 0.01
timesteps = 500000
viewer.render()

ctrl = np.zeros(17)
ctrl[0] = +0.00  # right shoulder 2
ctrl[15] = -0.00  # left shoulder 2
ctrl[14] = -0.00  # left shoulder 1
ctrl[11] = +0.00  # right shoulder 1
ctrl[10] = -0.00 # left knee
sim.data.ctrl[:] = ctrl
j = 0
k = 0
# 运行仿真并在每个时间步骤中进行渲染
for i in range(timesteps):
    sim.step()
    viewer.render()

    sim.data.ctrl[:] = ctrl

    # 打印质心相对位置
    torso_z = sim.data.qpos[2]
    #print(torso_z) 
    viewer.add_marker(pos=[0,0,torso_z], size=np.array([0.05, 0.05, 0.05]), rgba=np.array([1.0, 0, 0.0, 1]), type=const.GEOM_SPHERE)
    torso_x = sim.data.qpos[0]
    #print(torso_x)
    viewer.add_marker(pos=[torso_x,1,torso_z], size=np.array([0.05, 0.05, 0.05]), rgba=np.array([1.0, 0, 0.0, 1]), type=const.GEOM_SPHERE)

    # 一些乱七八遭的参考点
    viewer.add_marker(pos=[0,-0.14,0.4], size=np.array([0.1, 0.1, 0.1]), rgba=np.array([0, 0, 1.0, 1]), type=const.GEOM_SPHERE)
    viewer.add_marker(pos=[-1,0,1.7], size=np.array([0.01, 0.01, 0.01]), rgba=np.array([0, 0, 1.0, 1]), type=const.GEOM_SPHERE)
    viewer.add_marker(pos=[0,0,0.4], size=np.array([0.1, 0.1, 0.1]), rgba=np.array([0, 0, 1.0, 1]), type=const.GEOM_SPHERE)
    
    # 计算torso坐标系竖直分量
    quatanion = sim.data.qpos[3:7]
    Rm = R.from_quat(quatanion)  # Rotation matrix
    #rotation_matrix = Rm.as_matrix()
    rotation_matrix=quaternion_to_rotation_matrix(quatanion)
    vertical_direction = np.array([0, 0, 1])
    body_z_axis = rotation_matrix.dot(vertical_direction)
    dot_product = np.dot(body_z_axis, vertical_direction)

    print('==================================')
    print(sim.data.contact.flat.copy())
    

# 关闭仿真环境和渲染器
viewer.close()
sim.close()



In [3]:
def _get_steps_pos(x,z):
    # 读取当前机器人相对于台阶的x,y,z距离: 
    step_size_x, step_size_y, step_size_z = [0.6,0.3,0.3]
    x_w =x + step_size_x + 0.0001  # 机器人在全局的x坐标
    #x =  (x_w // step_size_x + 1)*step_size_x - x_w     # 机器人距离下一级台阶的距离
    x_list=[]
    for i in range(7):
        x_ = x_w - 0.1 + i*0.1
        z_ = z - (x_ // step_size_x)*step_size_z # 机器人当前的距离地面（台阶）的高度
        x_list.append(z_)

    return x_list


In [12]:
import numpy as np
c = _get_steps_pos(-.1,1.4)
a = np.array([1,2,3,4])
print(a)
print(type(a))
a = np.append(a,c)
print(a)

[1 2 3 4]
<class 'numpy.ndarray'>
[1.  2.  3.  4.  1.4 1.4 1.1 1.1 1.1 1.1 1.1]


In [1]:
class A():
    def __init__(self,):
        print('def A')
        self.name = 'asdwvw'
    def _update(self,):
        print(self.name)
        print('A UPDATE')

class B(A):
    def __init__(self,):
        print('def B')
        super().__init__()
    def _update(self,):
        print('B -UP')
        super()._update()

aa = A()
aa._update()
print('===')
bb = B()
bb._update()
print('====')

@classmethod
def _updateeee(self,a):
    print(a)
def new_method(cls:B,method:classmethod):
    cls._update=method
    pass
print('====')
B._update = _updateeee
bb._update('asddsda')

def A
A UPDATE
===
def B
def A
B -UP
A UPDATE
====
====
asddsda


In [2]:
from stable_baselines3 import SAC
for item in dir(SAC):  #top_k_metergroup是某类的一个实例化对象
    print(item)

__abstractmethods__
__annotations__
__class__
__delattr__
__dict__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__slots__
__str__
__subclasshook__
__weakref__
_abc_impl
_convert_train_freq
_create_aliases
_dump_logs
_excluded_save_params
_get_policy_from_name
_get_torch_save_params
_init_callback
_on_step
_sample_action
_setup_learn
_setup_lr_schedule
_setup_model
_store_transition
_update_current_progress_remaining
_update_info_buffer
_update_learning_rate
_wrap_env
collect_rollouts
get_env
get_parameters
get_vec_normalize_env
learn
load
load_replay_buffer
logger
policy_aliases
predict
save
save_replay_buffer
set_env
set_logger
set_parameters
set_random_seed
train
