# 检查强化学习控制器model

In [7]:
# ------- 来自于mujoco150在win+py3.9下的矫情的要求 --------
# 手动添加mujoco路径
import os
from getpass import getuser
user_id = getuser()
os.add_dll_directory(f"C://Users//{user_id}//.mujoco//mujoco200//bin")
os.add_dll_directory(f"C://Users//{user_id}//.mujoco//mujoco-py-2.0.2.0//mujoco_py")
# -------------------------------------------------------
import time
import argparse
import sys
import gym_custom_env       # 注册自定义环境
import gym
import numpy as np
import pybullet_envs
from stable_baselines3 import SAC, TD3, PPO
from mujoco_py.generated import const
from collections import deque

In [8]:
env = gym.make('HumanoidCustomEnv-v0')
#env.render(mode="human")
save_path = "sb3model/HumanoidCustomEnv-v0/2e6_t4_sac_HumanoidCustomEnv-v0/best_model.zip"

sac_model = SAC.load(save_path, env=env)
ppo_model = PPO.load('sb3model/HumanoidCustomEnv-v0/2e7_t10_cpu6_ppo_HumanoidCustomEnv-v0/best_model.zip',env=env)

============ HUMANOID CUSTOM ENV ============
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [9]:
# 手动设置policy_kwargs=dict(net_arch=[256, 256])的sac策略网络
sac_model.policy

SACPolicy(
  (actor): Actor(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (latent_pi): Sequential(
      (0): Linear(in_features=294, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (mu): Linear(in_features=256, out_features=17, bias=True)
    (log_std): Linear(in_features=256, out_features=17, bias=True)
  )
  (critic): ContinuousCritic(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (qf0): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=1, bias=True)
    )
    (qf1): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=2

In [10]:
# 手动设置policy_kwargs=dict(net_arch=[256, 256])的PPO策略网络
ppo_model.policy

ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential(
      (0): Linear(in_features=294, out_features=256, bias=True)
      (1): Tanh()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): Tanh()
    )
    (policy_net): Sequential()
    (value_net): Sequential()
  )
  (action_net): Linear(in_features=256, out_features=17, bias=True)
  (value_net): Linear(in_features=256, out_features=1, bias=True)
)

In [11]:
# PPO的默认策略网络
default_ppo_model = PPO.load('sb3model/HumanoidCustomEnv-v0/2e6_t4_ppo_HumanoidCustomEnv-v0.zip',env=env)
default_ppo_model.policy

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential()
    (policy_net): Sequential(
      (0): Linear(in_features=294, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=294, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
  )
  (action_net): Linear(in_features=64, out_features=17, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)

In [13]:
# SAC的默认策略网络
default_sac_model = SAC.load('sb3model/HumanoidCustomEnv-v0/2e6_t0_sac_HumanoidCustomEnv-v0.zip',env=env)
default_sac_model.policy
default_sac_model.predict

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


SACPolicy(
  (actor): Actor(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (latent_pi): Sequential(
      (0): Linear(in_features=294, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (mu): Linear(in_features=256, out_features=17, bias=True)
    (log_std): Linear(in_features=256, out_features=17, bias=True)
  )
  (critic): ContinuousCritic(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (qf0): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=1, bias=True)
    )
    (qf1): Sequential(
      (0): Linear(in_features=311, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=2

In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R


In [15]:
pos = np.array([0 , 1, 0, -0.35, 1.23e-06, 4.18e-08, 0.39,1,2])
quatanion = pos[3:7]
sum = np.linalg.norm(quatanion)
print(np.sum(quatanion*quatanion))
print(quatanion)
Rm = R.from_quat(quatanion)  # Rotation matrix
rotation_matrix = Rm.as_matrix()
print(rotation_matrix)
vertical_direction = np.array([0, 0, 1])
body_z_axis = rotation_matrix.dot(vertical_direction)
print(body_z_axis)
sum = np.linalg.norm(body_z_axis)
print(sum)
# 计算z轴方向向量与竖直向上方向向量的点积
dot_product = np.dot(body_z_axis, vertical_direction)
print(dot_product)

0.27460000000151463
[-3.50e-01  1.23e-06  4.18e-08  3.90e-01]
[[ 1.00000000e+00 -3.25420248e-06  3.38725419e-06]
 [-3.01673707e-06  1.07793154e-01  9.94173343e-01]
 [-3.60036417e-06 -9.94173343e-01  1.07793154e-01]]
[3.38725419e-06 9.94173343e-01 1.07793154e-01]
1.0
0.10779315367197961


In [5]:
def sumA(a,b):
    return a*2+b
def sumB(a,b):
    return a+b*3
class A():
    def __init__(self,mode):
        if mode == 1:
            self.sum = sumA
        if mode == 2:
            self.sum = sumB

a = A(2)

c = a.sum(1,2)
print(c)

7
